### ISSUE TITLE
Firebase crashlytics No support for JavaScript based apps. So why this Plugin then? 

### ISSUE THREAD

**Issue by Sampath-Lokuge** [rdlabo-team/capacitor-firebase-crashlytics#2]
Hi,

Former Firebase Team member says:

`Crashlytics does not work with React Native, nor any JavaScript environment. As you can see from the documentation, it only works for native Android and iOS apps, and Unity games built on top of those platforms.`

Link: https://stackoverflow.com/questions/56883167/i-cant-see-crash-report-of-android-in-firebase-console/56883246#56883246

So what does this plugin do then?

**Comment by rdlabo** [comment]
@Sampath-Lokuge This plugin check Native plugin(or Code) crash. nor check JavaScript. Thanks.
